import { readFile } from 'node:fs/promises';
const [web, native] = await Promise.all([readFile(new URL('../src/web.tsx', import.meta.url), 'utf8'), readFile(new URL('../src/native.tsx', import.meta.url), 'utf8')]);
for (const name of ['Text', 'Heading', 'Surface', 'Divider', 'IconButton', 'Badge', 'Avatar', 'Card', 'ListItem', 'EmptyState', 'SkeletonRegion', 'Table']) if (!web.includes(`function ${name}`)) throw new Error(`Missing Web ${name}`);
for (const name of ['NativeText', 'NativeHeading', 'NativeSurface', 'NativeDivider', 'NativeIconButton', 'NativeBadge', 'NativeAvatar', 'NativeCard', 'NativeListItem', 'NativeEmptyState', 'NativeSkeletonRegion']) if (!native.includes(`function ${name}`)) throw new Error(`Missing Native ${name}`);
if (native.includes('function NativeTable')) throw new Error('Table must remain Web-only; use a list/card product pattern on Native.');
if (web.includes('className') && !web.includes("'className'")) throw new Error('Unbounded className escape hatch.');
if (!web.includes(':focus-visible')) throw new Error('IconButton must preserve keyboard focus visibility.');
if (!web.includes('textStyleByRole') || !web.includes('webTextColor') || !native.includes('typography.textStyle') || !native.includes('nativeTextColor')) throw new Error('Typed text-style or color token consumption is missing.');
const { textColorByTone, textStyleByRole } = await import('../src/contracts.ts');
if (textStyleByRole.body !== 'text-m-regular' || textStyleByRole.display !== 'title-xxl-bold' || textColorByTone.onBrand !== 'fg-on-brand') throw new Error('Legacy typography aliases do not map to the new token contract.');
const { assertBadgeContract } = await import('../src/contracts.ts'); assertBadgeContract({ label: '배송 중' }); for (const value of [{ label: ' ' }, { label: '상태', tone: 'warning' }, { label: '상태', size: 'lg' }]) { let threw = false; try { assertBadgeContract(value); } catch { threw = true; } if (!threw) throw new Error(`Badge accepted invalid contract ${JSON.stringify(value)}`); }
const { assertAvatarContract, getAvatarInitials } = await import('../src/contracts.ts'); assertAvatarContract({ name: '김경석', accessibility: { kind: 'decorative' } }); for (const [name, expected] of [['김경석', '김경'], ['openai', 'OP'], ['👩‍💻Kim', '👩‍💻K'], ['e\u0301mile', 'E\u0301M']]) if (getAvatarInitials(name) !== expected) throw new Error(`Avatar grapheme initials are incorrect for ${name}.`);
for (const value of [{ name: ' ', accessibility: { kind: 'decorative' } }, { name: '김경석', size: 'xl', accessibility: { kind: 'decorative' } }, { name: '김경석', sourceUri: 'http://example.com/a.png', accessibility: { kind: 'decorative' } }, { name: '김경석', sourceUri: 'https://', accessibility: { kind: 'decorative' } }, { name: '김경석', sourceUri: 'https://user:pass@example.com/a.png', accessibility: { kind: 'decorative' } }, { name: '김경석', sourceUri: 'https://example.com/bad path', accessibility: { kind: 'decorative' } }, { name: '김경석', accessibility: { kind: 'labelled', label: ' ' } }, { name: '김경석', accessibility: { kind: 'unknown' } }]) { let threw = false; try { assertAvatarContract(value); } catch { threw = true; } if (!threw) throw new Error(`Avatar accepted invalid contract ${JSON.stringify(value)}`); }
const { createElement, Fragment } = await import('react'); const { assertCardContract, assertNativeCardContract } = await import('../src/contracts.ts'); assertCardContract({ children: '주문 요약' }); for (const value of [{ children: null }, { children: false }, { children: true }, { children: [] }, { children: createElement(Fragment, null) }, { children: ' ' }, { children: '내용', variant: 'floating' }, { children: '내용', accessibilityLabel: ' ' }]) { let threw = false; try { assertCardContract(value); } catch { threw = true; } if (!threw) throw new Error(`Card accepted invalid contract ${JSON.stringify(value)}`); } let nativeLabelRejected = false; try { assertNativeCardContract({ children: '내용', accessibilityLabel: '요약' }); } catch { nativeLabelRejected = true; } if (!nativeLabelRejected) throw new Error('NativeCard accepted an inaccessible grouping label.');
const { assertListItemContract, getListItemAccessibleName } = await import('../src/contracts.ts'); assertListItemContract({ title: '배송 현황', action: { onAction: () => undefined, onActionError: () => undefined }, trailing: 'chevron', loading: true }); if (getListItemAccessibleName({ title: '배송 현황', description: '새벽 배송 예정', metadata: '오후 6:00', action: { onAction: () => undefined, onActionError: () => undefined } }) !== '배송 현황, 새벽 배송 예정, 오후 6:00') throw new Error('ListItem default accessible name is incomplete.'); for (const value of [{ title: ' ' }, { title: '배송', leadingIcon: 'unknown' }, { title: '배송', trailing: 'add' }, { title: '배송', trailing: 'chevron' }, { title: '배송', action: { onAction: () => undefined } }, { title: '배송', disabled: 'yes' }, { title: '배송', loading: true }, { title: '배송', loading: 'yes', action: { onAction: () => undefined, onActionError: () => undefined } }]) { let threw = false; try { assertListItemContract(value); } catch { threw = true; } if (!threw) throw new Error(`ListItem accepted invalid contract ${JSON.stringify(value)}`); }
const { assertEmptyStateContract } = await import('../src/contracts.ts'); assertEmptyStateContract({ title: '주문 내역이 없어요', description: '새 주문을 추가해 주세요.', action: { label: '새 주문', onAction: () => undefined, onActionError: () => undefined } }); for (const value of [{ title: ' ', description: '설명' }, { title: '제목', description: ' ' }, { title: '제목', description: '설명', icon: 'unknown' }, { title: '제목', description: '설명', action: { label: ' ', onAction: () => undefined, onActionError: () => undefined } }, { title: '제목', description: '설명', action: { label: '다시 시도', onAction: () => undefined } }]) { let threw = false; try { assertEmptyStateContract(value); } catch { threw = true; } if (!threw) throw new Error(`EmptyState accepted invalid contract ${JSON.stringify(value)}`); }
const { assertSkeletonContract } = await import('../src/contracts.ts'); for (const shape of ['text', 'block', 'circle']) for (const size of ['sm', 'md', 'lg', 'full']) if (!(shape === 'circle' && size === 'full')) assertSkeletonContract({ shape, size }); for (const value of [{ shape: 'line' }, { size: 'xl' }, { shape: 'circle', size: 'full' }]) { let threw = false; try { assertSkeletonContract(value); } catch { threw = true; } if (!threw) throw new Error(`Skeleton accepted invalid contract ${JSON.stringify(value)}`); } if (!web.includes('prefers-reduced-motion') || !native.includes('useReducedMotion') || !native.includes('Animated.loop')) throw new Error('Skeleton reduced-motion contract is missing.');
const { assertSkeletonRegionContract, getSkeletonRecipeCount } = await import('../src/contracts.ts'); assertSkeletonRegionContract({ accessibilityLabel: '불러오는 중', items: [{ size: 'md' }] }); assertSkeletonRegionContract({ accessibilityLabel: '목록을 불러오는 중', recipe: 'list-item' }); if (getSkeletonRecipeCount('list-item') !== 3 || getSkeletonRecipeCount('card') !== 1) throw new Error('Skeleton recipe default count is incorrect.'); for (const value of [{ accessibilityLabel: ' ', items: [{ size: 'md' }] }, { accessibilityLabel: '불러오는 중', items: [] }, { accessibilityLabel: '불러오는 중', items: [{ shape: 'circle', size: 'full' }] }, { accessibilityLabel: '불러오는 중', items: [{ size: 'md' }], recipe: 'card' }, { accessibilityLabel: '불러오는 중', recipe: 'unknown' }, { accessibilityLabel: '불러오는 중', recipe: 'card', count: 9 }]) { let threw = false; try { assertSkeletonRegionContract(value); } catch { threw = true; } if (!threw) throw new Error(`SkeletonRegion accepted invalid contract ${JSON.stringify(value)}`); }
if (!web.includes('motion-duration-skeleton-pulse') || !native.includes('@kimgseok/design-motion/native') || native.includes('duration: 320')) throw new Error('Skeleton must consume semantic motion recipes.');
if (!web.includes('onPointerCancel') || !web.includes('<Spinner decorative') || !native.includes('NativeIconButtonLoadingIndicator') || !native.includes('useReducedMotion')) throw new Error('IconButton motion-safe busy or pointer-cancel contract is missing.');
const { assertTableContract } = await import('../src/contracts.ts'); const table = { caption: '주문 요약', columns: [{ id: 'product', label: '상품' }, { id: 'amount', label: '금액', align: 'end' }], rows: [{ id: 'one', cells: { product: '배송 상품', amount: '12,000원' } }] }; assertTableContract(table); for (const value of [{ ...table, caption: ' ' }, { ...table, columns: [] }, { ...table, rows: [] }, { ...table, columns: [{ id: 'same', label: '첫 번째' }, { id: 'same', label: '두 번째' }] }, { ...table, rows: [{ id: 'one', cells: { product: '상품' } }] }]) { let threw = false; try { assertTableContract(value); } catch { threw = true; } if (!threw) throw new Error(`Table accepted invalid contract ${JSON.stringify(value)}`); }
