import { readFile } from 'node:fs/promises';
import { createElement } from 'react';
const [web, native] = await Promise.all([readFile(new URL('../src/web.tsx', import.meta.url), 'utf8'), readFile(new URL('../src/native.tsx', import.meta.url), 'utf8')]);
for (const marker of ['role="tablist"', 'role="tab"', 'role="tabpanel"', 'event.key === "ArrowRight"', 'event.key === "Home"', 'aria-selected']) if (!web.includes(marker)) throw new Error(`Web Tabs contract missing ${marker}`);
for (const marker of ['accessibilityRole="tablist"', 'accessibilityRole="tab"', 'selected', 'minHeight: 44']) if (!native.includes(marker)) throw new Error(`Native Tabs contract missing ${marker}`);
const contracts = await readFile(new URL('../src/contracts.ts', import.meta.url), 'utf8');
for (const marker of ['items.length === 0', 'values.size !== items.length', '!items.some', '!selected || selected.disabled']) if (!contracts.includes(marker)) throw new Error(`Tabs invariant missing ${marker}`);
const { assertTabsContract } = await import('../src/contracts.ts');
const valid = [{ value: 'one', label: '하나', content: null }];
assertTabsContract(valid, 'one', '예시 탭');
for (const [items, value] of [[[], 'one'], [[{ value: 'one', label: '하나', content: null }, { value: 'one', label: '둘', content: null }], 'one'], [[{ value: 'one', label: '하나', disabled: true, content: null }], 'one'], [valid, 'missing'], [[{ value: ' ', label: '빈 값', content: null }], ' '], [[{ value: 'one', label: ' ', content: null }], 'one']]) {
  let threw = false; try { assertTabsContract(items, value, '예시 탭'); } catch { threw = true; }
  if (!threw) throw new Error(`Tabs invariant did not reject ${JSON.stringify({ items, value })}`);
}
let blankGroupThrew = false; try { assertTabsContract(valid, 'one', ' '); } catch { blankGroupThrew = true; }
if (!blankGroupThrew) throw new Error('Tabs invariant did not reject a blank accessibilityLabel.');
for (const marker of ['function SegmentedControl', 'role="radiogroup"', 'role="radio"']) if (!web.includes(marker)) throw new Error(`Web SegmentedControl missing ${marker}`);
for (const marker of ['function NativeSegmentedControl', 'accessibilityRole="radiogroup"', 'accessibilityRole="radio"']) if (!native.includes(marker)) throw new Error(`Native SegmentedControl missing ${marker}`);
const { assertSegmentedControlContract } = await import('../src/contracts.ts');
const segments = [{ value: 'one', label: '하나' }, { value: 'two', label: '둘' }]; assertSegmentedControlContract(segments, 'one', '보기');
for (const [items, value, label] of [[[segments[0]], 'one', '보기'], [[...segments, { value: 'three', label: '셋' }, { value: 'four', label: '넷' }, { value: 'five', label: '다섯' }], 'one', '보기'], [[segments[0], { ...segments[0] }], 'one', '보기'], [segments, 'missing', '보기'], [[{ ...segments[0], disabled: true }, { ...segments[1], disabled: true }], 'one', '보기'], [segments, 'one', ' ']]) { let threw = false; try { assertSegmentedControlContract(items, value, label); } catch { threw = true; } if (!threw) throw new Error(`SegmentedControl invariant did not reject ${JSON.stringify({ items, value, label })}`); }
for (const items of [[{ value: ' ', label: '하나' }, segments[1]], [{ value: 'one', label: ' ' }, segments[1]]]) { let threw = false; try { assertSegmentedControlContract(items, 'one', '보기'); } catch { threw = true; } if (!threw) throw new Error('SegmentedControl invariant accepted a blank item value or label.'); }
for (const marker of ['function Chip', 'aria-pressed', 'onSelectedChange(!selected)']) if (!web.includes(marker)) throw new Error(`Web Chip missing ${marker}`);
for (const marker of ['function NativeChip', 'accessibilityState={{ disabled, selected }}', 'minHeight: 44']) if (!native.includes(marker)) throw new Error(`Native Chip missing ${marker}`);
if (!web.includes('function ChipGroup') || !native.includes('function NativeChipGroup') || !native.includes('accessibilityRole="header"')) throw new Error('ChipGroup platform contracts missing.');
const { assertChipGroupContract } = await import('../src/contracts.ts'); const ExpectedChip = () => null; const Other = () => null;
assertChipGroupContract('필터', createElement(ExpectedChip, { label: '정상', selected: false, onSelectedChange() {} }), ExpectedChip);
for (const [label, children] of [[' ', createElement(ExpectedChip)], ['필터', []], ['필터', createElement(Other)], ['필터', createElement('button')]]) { let threw = false; try { assertChipGroupContract(label, children, ExpectedChip); } catch { threw = true; } if (!threw) throw new Error('ChipGroup invariant accepted invalid label or child.'); }
const { assertFilterBarContract } = await import('../src/contracts.ts'); const filters = [{ value: 'free', label: '무료 배송' }, { value: 'tomorrow', label: '내일 도착' }, { value: 'disabled', label: '품절', disabled: true }]; assertFilterBarContract({ accessibilityLabel: '상품 필터', items: filters, selectedValues: ['free'], onSelectedValuesChange() {} });
for (const value of [{ accessibilityLabel: ' ', items: filters, selectedValues: [], onSelectedValuesChange() {} }, { accessibilityLabel: '필터', items: [], selectedValues: [], onSelectedValuesChange() {} }, { accessibilityLabel: '필터', items: [...filters, { value: 'free', label: '중복' }], selectedValues: [], onSelectedValuesChange() {} }, { accessibilityLabel: '필터', items: [{ value: 'free', label: '무료 배송', disabled: 'false' }], selectedValues: [], onSelectedValuesChange() {} }, { accessibilityLabel: '필터', items: filters, selectedValues: ['disabled'], onSelectedValuesChange() {} }, { accessibilityLabel: '필터', items: filters, selectedValues: ['missing'], onSelectedValuesChange() {} }, { accessibilityLabel: '필터', items: filters, selectedValues: ['free', 'free'], onSelectedValuesChange() {} }]) { let threw = false; try { assertFilterBarContract(value); } catch { threw = true; } if (!threw) throw new Error('FilterBar invariant accepted invalid state.'); }
for (const marker of ['function FilterBar', 'ChipGroup', '선택 해제']) if (!web.includes(marker)) throw new Error(`Web FilterBar missing ${marker}`);
for (const marker of ['function NativeFilterBar', 'NativeChipGroup', 'accessibilityRole="header"']) if (!native.includes(marker)) throw new Error(`Native FilterBar missing ${marker}`);
const { assertPaginationContract, getPaginationItems, shouldAnnounceNativePagination } = await import('../src/contracts.ts');
assertPaginationContract({ accessibilityLabel: '검색 결과 페이지', page: 6, totalPages: 20 });
for (const value of [{ accessibilityLabel: ' ', page: 1, totalPages: 1 }, { accessibilityLabel: '페이지', page: 0, totalPages: 1 }, { accessibilityLabel: '페이지', page: 2, totalPages: 1 }, { accessibilityLabel: '페이지', page: 1.5, totalPages: 2 }, { accessibilityLabel: '페이지', page: 1, totalPages: 0 }, { accessibilityLabel: '페이지', page: 1, totalPages: Infinity }]) { let threw = false; try { assertPaginationContract(value); } catch { threw = true; } if (!threw) throw new Error(`Pagination invariant accepted ${JSON.stringify(value)}`); }
if (JSON.stringify(getPaginationItems(1, 3)) !== JSON.stringify([1, 2, 3])) throw new Error('Pagination small range is incorrect.');
if (JSON.stringify(getPaginationItems(6, 20)) !== JSON.stringify([1, 'ellipsis', 5, 6, 7, 'ellipsis', 20])) throw new Error('Pagination middle range is incorrect.');
for (const [page, expected] of [[1, [1, 2, 'ellipsis', 8]], [2, [1, 2, 3, 'ellipsis', 8]], [4, [1, 'ellipsis', 3, 4, 5, 'ellipsis', 8]], [7, [1, 'ellipsis', 6, 7, 8]], [8, [1, 'ellipsis', 7, 8]]]) if (JSON.stringify(getPaginationItems(page, 8)) !== JSON.stringify(expected)) throw new Error(`Pagination edge range is incorrect for page ${page}.`);
if (shouldAnnounceNativePagination('ios', true) || !shouldAnnounceNativePagination('ios', false) || shouldAnnounceNativePagination('android', false)) throw new Error('Native Pagination announcement policy is incorrect.');
for (const marker of ['function Pagination', 'aria-current', 'getPaginationItems']) if (!web.includes(marker)) throw new Error(`Web Pagination missing ${marker}`);
for (const marker of ['function NativePagination', 'accessibilityLiveRegion="polite"', 'shouldAnnounceNativePagination', 'announceForAccessibility', '이전 페이지', '다음 페이지']) if (!native.includes(marker)) throw new Error(`Native Pagination missing ${marker}`);
const { assertAppBarContract } = await import('../src/contracts.ts');
const appBarAction = { accessibilityLabel: '뒤로 가기', icon: 'chevron-left', onAction() {}, onActionError() {} }; assertAppBarContract({ title: '주문 상세', leadingAction: appBarAction, trailingActions: [] });
for (const value of [{ title: ' ' }, { title: '제목', subtitle: ' ' }, { title: '제목', leadingAction: { ...appBarAction, accessibilityLabel: ' ' } }, { title: '제목', trailingActions: [appBarAction, appBarAction, appBarAction] }, { title: '제목', leadingAction: appBarAction, trailingActions: [{ ...appBarAction }] }, { title: '제목', leadingAction: { ...appBarAction, onAction: undefined } }, { title: '제목', leadingAction: { ...appBarAction, onActionError: undefined } }]) { let threw = false; try { assertAppBarContract(value); } catch { threw = true; } if (!threw) throw new Error(`AppBar invariant accepted ${JSON.stringify(value)}`); }
for (const marker of ['function AppBar', '<header', '<h1', 'IconButton']) if (!web.includes(marker)) throw new Error(`Web AppBar missing ${marker}`);
for (const marker of ['function NativeAppBar', 'useSafeAreaInsets', 'NativeIconButton', 'accessibilityRole="header"']) if (!native.includes(marker)) throw new Error(`Native AppBar missing ${marker}`);
const { assertBreadcrumbContract } = await import('../src/contracts.ts'); const crumbs = [{ label: '홈', href: '/' }, { label: '상품' }]; assertBreadcrumbContract({ accessibilityLabel: '현재 위치', items: crumbs });
for (const value of [{ accessibilityLabel: ' ', items: crumbs }, { accessibilityLabel: '현재 위치', items: [crumbs[0]] }, { accessibilityLabel: '현재 위치', items: [...crumbs, { label: '셋', href: '/3' }, { label: '넷', href: '/4' }, { label: '다섯', href: '/5' }, { label: '여섯' }] }, { accessibilityLabel: '현재 위치', items: [{ label: ' ', href: '/' }, crumbs[1]] }, { accessibilityLabel: '현재 위치', items: [{ label: '홈' }, crumbs[1]] }, { accessibilityLabel: '현재 위치', items: [{ label: '홈', href: '/' }, { label: '상품', href: '/products' }] }, { accessibilityLabel: '현재 위치', items: [{ label: '홈', href: '/' }, { label: '홈' }] }]) { let threw = false; try { assertBreadcrumbContract(value); } catch { threw = true; } if (!threw) throw new Error(`Breadcrumb invariant accepted ${JSON.stringify(value)}`); }
for (const href of ['javascript:alert(1)', 'data:text/html,bad', '//evil.test/path', '/bad path', '/bad\npath', '/\\evil.test/path', '/\\\\evil.test/path']) { let threw = false; try { assertBreadcrumbContract({ accessibilityLabel: '현재 위치', items: [{ label: '홈', href }, crumbs[1]] }); } catch { threw = true; } if (!threw) throw new Error(`Breadcrumb accepted unsafe href ${JSON.stringify(href)}`); }
for (const marker of ['function Breadcrumb', '<nav', '<ol', 'aria-current="page"', 'chevron-right']) if (!web.includes(marker)) throw new Error(`Web Breadcrumb missing ${marker}`);
