import { useEffect, useRef, useState, type ComponentRef } from 'react';
import { AccessibilityInfo, findNodeHandle, Platform, Pressable, ScrollView, Text, useColorScheme, View, type ScrollView as ScrollViewType } from 'react-native';
import { getNativeTheme } from '@kimgseok/design-tokens/native';
import { NativeIconButton } from '@kimgseok/design-primitives/native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { assertAppBarContract, assertChipGroupContract, assertFilterBarContract, assertPaginationContract, assertSegmentedControlContract, assertTabsContract, shouldAnnounceNativePagination, type AppBarContract, type ChipContract, type ChipGroupContract, type FilterBarContract, type PaginationContract, type SegmentedControlContract, type TabsContract } from './contracts';

export function NativeTabs({ accessibilityLabel, items, value, onValueChange }: TabsContract) {
  assertTabsContract(items, value, accessibilityLabel);
  const theme = getNativeTheme(useColorScheme() === 'dark' ? 'dark' : 'light', Platform.OS === 'android' ? 'android' : 'ios');
  const active = items.find((item) => item.value === value)!;
  const scrollRef = useRef<ScrollViewType>(null); const [positions, setPositions] = useState<Record<string, { width: number; x: number }>>({}); const [viewportWidth, setViewportWidth] = useState(0);
  useEffect(() => { const layout = positions[value]; if (!layout || !viewportWidth) return; const centeredX = layout.x - Math.max(12, (viewportWidth - layout.width) / 2); scrollRef.current?.scrollTo({ animated: false, x: Math.max(0, centeredX) }); }, [positions, value, viewportWidth]);
  return <View style={{ gap: 16 }}><ScrollView horizontal accessibilityLabel={accessibilityLabel} accessibilityRole="tablist" contentContainerStyle={{ borderBottomColor: theme.color.semantic.border.subtle, borderBottomWidth: 1, gap: 4 }} onLayout={(event) => setViewportWidth(event.nativeEvent.layout.width)} ref={scrollRef} showsHorizontalScrollIndicator={false}>{items.map((item) => { const selected = item.value === active.value; return <Pressable accessibilityLabel={item.label} accessibilityRole="tab" accessibilityState={{ disabled: item.disabled, selected }} disabled={item.disabled} key={item.value} onLayout={(event) => { const { width, x } = event.nativeEvent.layout; setPositions((current) => current[item.value]?.x === x && current[item.value]?.width === width ? current : { ...current, [item.value]: { width, x } }); }} onPress={() => onValueChange(item.value)} style={{ borderBottomColor: selected ? theme.color.semantic.action.primary.bg : 'transparent', borderBottomWidth: 2, justifyContent: 'center', maxWidth: viewportWidth ? Math.max(44, viewportWidth - 24) : undefined, minHeight: 44, paddingHorizontal: 12 }}><Text accessible={false} numberOfLines={1} style={[theme.typography.role.label, { color: item.disabled ? theme.color.semantic.fg.disabled : selected ? theme.color.semantic.fg.primary : theme.color.semantic.fg.secondary }]}>{item.label}</Text></Pressable>; })}</ScrollView><View>{active.content}</View></View>;
}

export function NativeSegmentedControl({ accessibilityLabel, items, value, onValueChange }: SegmentedControlContract) { assertSegmentedControlContract(items, value, accessibilityLabel); const theme = getNativeTheme(useColorScheme() === 'dark' ? 'dark' : 'light', Platform.OS === 'android' ? 'android' : 'ios'); return <View accessibilityLabel={accessibilityLabel} accessibilityRole="radiogroup" style={{ alignSelf: 'stretch', backgroundColor: theme.color.semantic.bg.surface, borderRadius: theme.foundation.radius.lg, flexDirection: 'row', gap: 2, maxWidth: '100%', minWidth: 0, padding: 4 }}>{items.map((item) => { const selected = item.value === value; return <Pressable accessibilityLabel={item.label} accessibilityRole="radio" accessibilityState={{ checked: selected, disabled: item.disabled }} disabled={item.disabled} key={item.value} onPress={() => onValueChange(item.value)} style={[selected ? theme.foundation.elevation['1'] : undefined, { alignItems: 'center', backgroundColor: selected ? theme.color.semantic.bg.raised : 'transparent', borderRadius: theme.foundation.radius.md, flex: 1, justifyContent: 'center', minHeight: 44, minWidth: 0, paddingHorizontal: 12 }]}><Text accessible={false} ellipsizeMode="tail" numberOfLines={1} style={[theme.typography.role.label, { color: item.disabled ? theme.color.semantic.fg.disabled : selected ? theme.color.semantic.fg.primary : theme.color.semantic.fg.secondary }]}>{item.label}</Text></Pressable>; })}</View>; }

export function NativeChip({ label, selected, disabled = false, onSelectedChange }: ChipContract) { if (!label.trim()) throw new Error('Chip label must not be blank.'); const theme = getNativeTheme(useColorScheme() === 'dark' ? 'dark' : 'light', Platform.OS === 'android' ? 'android' : 'ios'); const selection = theme.color.semantic.selection; return <Pressable accessibilityLabel={label} accessibilityRole="button" accessibilityState={{ disabled, selected }} disabled={disabled} onPress={() => onSelectedChange(!selected)} style={({ pressed }) => ({ alignItems: 'center', alignSelf: 'flex-start', backgroundColor: disabled ? selection.disabledBg : selected ? selection.selectedBg : pressed ? theme.color.semantic.bg.surface : selection.unselectedBg, borderColor: selected ? selection.selectedBg : selection.unselectedBorder, borderRadius: 999, borderWidth: 1, justifyContent: 'center', maxWidth: '100%', minHeight: 44, minWidth: 0, paddingHorizontal: 14 })}><Text accessible={false} ellipsizeMode="tail" numberOfLines={1} style={[theme.typography.role.label, { color: disabled ? selection.disabledFg : selected ? selection.selectedFg : theme.color.semantic.fg.primary }]}>{label}</Text></Pressable>; }
export function NativeChipGroup({ accessibilityLabel, children }: ChipGroupContract) { assertChipGroupContract(accessibilityLabel, children, NativeChip); const theme = getNativeTheme(useColorScheme() === 'dark' ? 'dark' : 'light', Platform.OS === 'android' ? 'android' : 'ios'); return <View style={{ gap: 8, maxWidth: '100%' }}><Text accessibilityRole="header" style={[theme.typography.role.label, { color: theme.color.semantic.fg.secondary }]}>{accessibilityLabel}</Text><View style={{ flexDirection: 'row', flexWrap: 'wrap', gap: 8, maxWidth: '100%' }}>{children}</View></View>; }
export function NativeFilterBar({ accessibilityLabel, items, selectedValues, onSelectedValuesChange, clearLabel = '선택 해제', disabled = false, loading = false }: FilterBarContract) { assertFilterBarContract({ accessibilityLabel, items, selectedValues, onSelectedValuesChange, clearLabel, disabled, loading }); const theme = getNativeTheme(useColorScheme() === 'dark' ? 'dark' : 'light', Platform.OS === 'android' ? 'android' : 'ios'); const wasLoading = useRef(loading); const headingRef = useRef<ComponentRef<typeof Text>>(null); useEffect(() => { if (Platform.OS === 'ios' && loading && !wasLoading.current) void AccessibilityInfo.announceForAccessibility(`${accessibilityLabel}를 적용하는 중`); wasLoading.current = loading; }, [accessibilityLabel, loading]); const inactive = disabled || loading; const selected = new Set(selectedValues); const toggle = (value: string) => { if (!inactive) onSelectedValuesChange(selected.has(value) ? selectedValues.filter((item) => item !== value) : [...selectedValues, value]); }; const clear = () => { onSelectedValuesChange([]); setTimeout(() => { const node = findNodeHandle(headingRef.current); if (node !== null) AccessibilityInfo.setAccessibilityFocus(node); }, 0); }; return <View style={{ gap: 8, maxWidth: '100%' }}><Text accessibilityLiveRegion="polite" accessibilityRole="text" style={[theme.typography.role.caption, { color: theme.color.semantic.fg.secondary }]}>{loading ? `${accessibilityLabel}를 적용하는 중` : ''}</Text><View style={{ alignItems: 'center', flexDirection: 'row', gap: 8, justifyContent: 'space-between', minWidth: 0 }}><Text accessibilityRole="header" ellipsizeMode="tail" numberOfLines={2} ref={headingRef} style={[theme.typography.role.label, { color: theme.color.semantic.fg.primary, flex: 1, flexShrink: 1, minWidth: 0 }]}>{accessibilityLabel}</Text>{selectedValues.length ? <Pressable accessibilityLabel={clearLabel} accessibilityRole="button" accessibilityState={{ disabled: inactive }} disabled={inactive} onPress={clear} style={{ justifyContent: 'center', minHeight: 44, paddingHorizontal: 4 }}><Text style={[theme.typography.role.label, { color: inactive ? theme.color.semantic.fg.disabled : theme.color.semantic.fg.secondary, textDecorationLine: 'underline' }]}>{clearLabel}</Text></Pressable> : null}</View><View accessibilityLabel={`${accessibilityLabel} 옵션`} accessibilityState={{ busy: loading }} style={{ flexDirection: 'row', flexWrap: 'wrap', gap: 8, maxWidth: '100%' }}>{items.map((item) => <NativeChip disabled={inactive || item.disabled} key={item.value} label={item.label} onSelectedChange={() => toggle(item.value)} selected={selected.has(item.value)} />)}</View></View>; }

export function NativePagination({ accessibilityLabel, page, totalPages, disabled = false, onPageChange }: PaginationContract) { assertPaginationContract({ accessibilityLabel, page, totalPages }); const theme = getNativeTheme(useColorScheme() === 'dark' ? 'dark' : 'light', Platform.OS === 'android' ? 'android' : 'ios'); const mounted = useRef(false); const status = `${totalPages}페이지 중 ${page}페이지`; useEffect(() => { const isInitial = !mounted.current; mounted.current = true; if (shouldAnnounceNativePagination(Platform.OS, isInitial)) AccessibilityInfo.announceForAccessibility(status); }, [status]); const action = (label: string, target: number) => { const inactive = disabled || target < 1 || target > totalPages; return <Pressable accessibilityLabel={label} accessibilityRole="button" accessibilityState={{ disabled: inactive }} disabled={inactive} onPress={() => onPageChange(target)} style={({ pressed }) => ({ alignItems: 'center', backgroundColor: pressed && !inactive ? theme.color.semantic.bg.surface : theme.color.semantic.bg.raised, borderColor: theme.color.semantic.border.subtle, borderRadius: theme.foundation.radius.md, borderWidth: 1, flex: 1, justifyContent: 'center', minHeight: 44, minWidth: 0, opacity: inactive ? 0.5 : 1, paddingHorizontal: 12 })}><Text accessible={false} style={[theme.typography.role.label, { color: inactive ? theme.color.semantic.fg.disabled : theme.color.semantic.fg.primary }]}>{label}</Text></Pressable>; }; return <View style={{ gap: 8, maxWidth: '100%' }}><Text accessibilityRole="header" style={[theme.typography.role.label, { color: theme.color.semantic.fg.secondary }]}>{accessibilityLabel}</Text><Text accessibilityLabel={status} accessibilityLiveRegion="polite" accessibilityRole="text" style={[theme.typography.role.body, { color: theme.color.semantic.fg.primary, textAlign: 'center' }]}>{page} / {totalPages} 페이지</Text><View style={{ flexDirection: 'row', gap: 8 }}>{action('이전 페이지', page - 1)}{action('다음 페이지', page + 1)}</View></View>; }

export function NativeAppBar({ title, subtitle, leadingAction, trailingActions = [] }: AppBarContract) { assertAppBarContract({ title, subtitle, leadingAction, trailingActions }); const insets = useSafeAreaInsets(); const theme = getNativeTheme(useColorScheme() === 'dark' ? 'dark' : 'light', Platform.OS === 'android' ? 'android' : 'ios'); const action = (item: NonNullable<AppBarContract['leadingAction']>) => <NativeIconButton accessibilityLabel={item.accessibilityLabel} disabled={item.disabled} icon={item.icon} key={item.accessibilityLabel} loading={item.loading} onAction={item.onAction} onActionError={item.onActionError} size="sm" />; return <View style={{ alignItems: 'center', backgroundColor: theme.color.semantic.bg.canvas, borderBottomColor: theme.color.semantic.border.subtle, borderBottomWidth: 1, flexDirection: 'row', minHeight: 64 + insets.top, paddingBottom: 8, paddingHorizontal: 16, paddingTop: insets.top + 8 }}><View style={{ flex: 1, alignItems: 'flex-start' }}>{leadingAction ? action(leadingAction) : null}</View><View style={{ flexShrink: 1, minWidth: 0 }}><Text accessibilityRole="header" ellipsizeMode="tail" numberOfLines={1} style={[theme.typography.role.heading, { color: theme.color.semantic.fg.primary, textAlign: 'center' }]}>{title}</Text>{subtitle ? <Text ellipsizeMode="tail" numberOfLines={1} style={[theme.typography.role.caption, { color: theme.color.semantic.fg.secondary, textAlign: 'center' }]}>{subtitle}</Text> : null}</View><View style={{ alignItems: 'flex-end', flex: 1, flexDirection: 'row', gap: 4, justifyContent: 'flex-end' }}>{trailingActions.map(action)}</View></View>; }
