import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { assertCalendarContract, assertDatePickerContract, assertDateRangePickerContract, formatDateValue, isDateAllowed, parseDateValue } from "../src/contracts.ts";
const web = readFileSync(new URL("../src/web.tsx", import.meta.url), "utf8");
const native = readFileSync(new URL("../src/native.tsx", import.meta.url), "utf8");
assert.equal(formatDateValue(new Date(2026, 7, 4)), "2026-08-04");
assert.equal(parseDateValue("2026-02-29"), null);
assert.ok(parseDateValue("2028-02-29"));
assert.equal(isDateAllowed("2026-08-24", { min: "2026-08-24", max: "2026-08-30" }), true);
assert.equal(isDateAllowed("2026-08-23", { min: "2026-08-24" }), false);
assert.doesNotThrow(() => assertDatePickerContract({ label: "날짜", value: "2026-08-24", onValueChange() {} }));
assert.throws(() => assertDateRangePickerContract({ label: "기간", value: { start: "2026-08-25", end: "2026-08-24" }, onValueChange() {} }));
assert.throws(() => assertDateRangePickerContract({ label: "기간", value: { start: "", end: "2026-08-24" }, onValueChange() {} }));
assert.throws(() => assertCalendarContract({ accessibilityLabel: "달력", value: "2026-08-23", min: "2026-08-24", onValueChange() {} }));
for (const key of ["ArrowLeft", "ArrowRight", "ArrowUp", "ArrowDown", "Home", "End", "PageUp", "PageDown"]) assert.match(web, new RegExp(key));
for (const role of ['role="grid"', 'role="row"', 'role="gridcell"', 'aria-label={`${label}, ${displayValue}`}']) assert.ok(web.includes(role), `${role} anatomy is required`);
assert.doesNotMatch(web, /<button[^>]+role="gridcell"/);
assert.match(native, /assertDatePickerContract\(\{ \.\.\.props, value \}\)/);
assert.match(native, /assertDateRangePickerContract\(\{ \.\.\.props, value \}\)/);
assert.match(native, /renderPicker/);
for (const contract of ["<Modal", "onDismiss={onClose}", "onRequestClose={onClose}", "accessibilityViewIsModal", "announceForAccessibility", "useSafeAreaInsets", "formatDateForLocale", "kind: \"single\"", "kind: \"range\""]) assert.ok(native.includes(contract), `Native picker presentation contract missing: ${contract}`);
assert.match(native, /animationType=\{reduceMotion \? "none" : "slide"\}/);
assert.match(native, /@kimgseok\/design-motion\/native/);
for (const contract of ["resolveDatePickerMessages", "copy.previousMonth", "copy.nextMonth", "copy.chooseStartDate", "copy.chooseEndDate"]) assert.ok(web.includes(contract), `Date picker localisation contract missing: ${contract}`);
assert.match(web, /setDraft\(value\)/);
assert.match(web, /onValueChange\(completed\);\s*changeOpen\(false\)/);
assert.equal((await import("../src/contracts.ts")).resolveDatePickerMessages("en-US").chooseDate, "Choose a date");
console.log("date-picker source contract checks passed");
