"use client";

import { useId, useRef, useState, type InputHTMLAttributes, type SelectHTMLAttributes, type TextareaHTMLAttributes } from 'react';
import { assertDateTimeFieldContract, assertSearchFieldContract, assertSliderContract, normalizeSliderValue, type ChoiceContract, type DateTimeFieldContract, type FieldContract, type RadioOption, type SearchFieldContract, type SliderContract } from './contracts';

const labelStyle = { color: 'var(--kg-color-fg-primary)', display: 'block', fontFamily: 'var(--kg-typography-family-web)', fontSize: 'var(--kg-typography-role-label-font-size)', fontWeight: 'var(--kg-typography-role-label-font-weight)', lineHeight: 'var(--kg-typography-role-label-line-height)', marginBottom: 'var(--kg-foundation-space-2)' } as const;
const messageStyle = { display: 'block', fontFamily: 'var(--kg-typography-family-web)', fontSize: 'var(--kg-typography-role-caption-font-size)', lineHeight: 'var(--kg-typography-role-caption-line-height)', marginTop: 'var(--kg-foundation-space-1)' } as const;
const controlStyle = { background: 'var(--kg-color-bg-canvas)', border: '1px solid var(--kg-color-border-strong)', borderRadius: 'var(--kg-foundation-radius-md)', boxSizing: 'border-box', color: 'var(--kg-color-fg-primary)', fontFamily: 'var(--kg-typography-family-web)', fontSize: 'var(--kg-typography-role-body-font-size)', lineHeight: 'var(--kg-typography-role-body-line-height)', minHeight: 48, padding: 'var(--kg-foundation-space-3)', width: '100%' } as const;
const focusStyle = { outline: 'var(--kg-foundation-focus-ring-width) solid var(--kg-color-border-focus)', outlineOffset: 'var(--kg-foundation-focus-ring-offset)' } as const;

type TextFieldProps = FieldContract & Omit<InputHTMLAttributes<HTMLInputElement>, 'className' | 'style' | 'disabled' | 'required' | 'size'>;
export function TextField({ label, helpText, errorMessage, disabled, required, id: suppliedId, onBlur, onFocus, ...props }: TextFieldProps) {
  const generatedId = useId(); const id = suppliedId ?? generatedId; const messageId = `${id}-message`;
  const [focusVisible, setFocusVisible] = useState(false);
  return <label htmlFor={id} style={{ display: 'block' }}><span style={labelStyle}>{label}{required ? ' (필수)' : ''}</span><input {...props} aria-describedby={helpText && !errorMessage ? messageId : undefined} aria-errormessage={errorMessage ? messageId : undefined} aria-invalid={Boolean(errorMessage) || undefined} disabled={disabled} id={id} onBlur={(event) => { setFocusVisible(false); onBlur?.(event); }} onFocus={(event) => { setFocusVisible(event.currentTarget.matches(':focus-visible')); onFocus?.(event); }} required={required} style={{ ...controlStyle, ...(focusVisible ? focusStyle : {}), borderColor: errorMessage ? 'var(--kg-color-status-negative-border)' : undefined }} />{errorMessage || helpText ? <span id={messageId} role={errorMessage ? 'alert' : undefined} style={{ ...messageStyle, color: errorMessage ? 'var(--kg-color-status-negative-fg)' : 'var(--kg-color-fg-secondary)' }}>{errorMessage ?? helpText}</span> : null}</label>;
}

type TextAreaProps = FieldContract & Omit<TextareaHTMLAttributes<HTMLTextAreaElement>, 'className' | 'style' | 'disabled' | 'required'>;
export function TextArea({ label, helpText, errorMessage, disabled, required, id: suppliedId, onBlur, onFocus, ...props }: TextAreaProps) {
  const generatedId = useId(); const id = suppliedId ?? generatedId; const messageId = `${id}-message`;
  const [focusVisible, setFocusVisible] = useState(false);
  return <label htmlFor={id} style={{ display: 'block' }}><span style={labelStyle}>{label}{required ? ' (필수)' : ''}</span><textarea {...props} aria-describedby={helpText && !errorMessage ? messageId : undefined} aria-errormessage={errorMessage ? messageId : undefined} aria-invalid={Boolean(errorMessage) || undefined} disabled={disabled} id={id} onBlur={(event) => { setFocusVisible(false); onBlur?.(event); }} onFocus={(event) => { setFocusVisible(event.currentTarget.matches(':focus-visible')); onFocus?.(event); }} required={required} style={{ ...controlStyle, ...(focusVisible ? focusStyle : {}), borderColor: errorMessage ? 'var(--kg-color-status-negative-border)' : undefined, minHeight: 120, resize: 'vertical' }} />{errorMessage || helpText ? <span id={messageId} role={errorMessage ? 'alert' : undefined} style={{ ...messageStyle, color: errorMessage ? 'var(--kg-color-status-negative-fg)' : 'var(--kg-color-fg-secondary)' }}>{errorMessage ?? helpText}</span> : null}</label>;
}

export function Checkbox({ label, checked, disabled, onCheckedChange }: ChoiceContract) {
  const [focusVisible, setFocusVisible] = useState(false);
  return <label style={{ alignItems: 'center', color: disabled ? 'var(--kg-color-selection-disabled-fg)' : 'var(--kg-color-fg-primary)', display: 'inline-flex', fontFamily: 'var(--kg-typography-family-web)', gap: 8, minHeight: 44 }}><input checked={checked} disabled={disabled} onBlur={() => setFocusVisible(false)} onChange={(event) => onCheckedChange(event.currentTarget.checked)} onFocus={(event) => setFocusVisible(event.currentTarget.matches(':focus-visible'))} style={{ accentColor: 'var(--kg-color-selection-selected-bg)', height: 20, outline: focusVisible ? 'var(--kg-foundation-focus-ring-width) solid var(--kg-color-border-focus)' : 'none', outlineOffset: 'var(--kg-foundation-focus-ring-offset)', width: 20 }} type="checkbox" />{label}</label>;
}

export function Switch({ label, checked, disabled, onCheckedChange }: ChoiceContract) {
  const [focusVisible, setFocusVisible] = useState(false);
  return <label style={{ alignItems: 'center', color: disabled ? 'var(--kg-color-selection-disabled-fg)' : 'var(--kg-color-fg-primary)', display: 'inline-flex', fontFamily: 'var(--kg-typography-family-web)', gap: 8, minHeight: 44 }}><input aria-label={label} checked={checked} disabled={disabled} onBlur={() => setFocusVisible(false)} onChange={(event) => onCheckedChange(event.currentTarget.checked)} onFocus={(event) => setFocusVisible(event.currentTarget.matches(':focus-visible'))} role="switch" style={{ accentColor: 'var(--kg-color-selection-selected-bg)', height: 24, outline: focusVisible ? 'var(--kg-foundation-focus-ring-width) solid var(--kg-color-border-focus)' : 'none', outlineOffset: 'var(--kg-foundation-focus-ring-offset)', width: 40 }} type="checkbox" /><span aria-hidden="true">{label}</span></label>;
}

export function RadioGroup({ label, name, options, value, onValueChange }: { label: string; name: string; options: RadioOption[]; value: string; onValueChange: (value: string) => void }) {
  const [focusedValue, setFocusedValue] = useState<string>();
  return <fieldset style={{ border: 0, margin: 0, padding: 0 }}><legend style={labelStyle}>{label}</legend><div style={{ display: 'grid', gap: 4 }}>{options.map((option) => <label key={option.value} style={{ alignItems: 'center', color: option.disabled ? 'var(--kg-color-selection-disabled-fg)' : 'var(--kg-color-fg-primary)', display: 'flex', fontFamily: 'var(--kg-typography-family-web)', gap: 8, minHeight: 44 }}><input checked={option.value === value} disabled={option.disabled} name={name} onBlur={() => setFocusedValue(undefined)} onChange={() => onValueChange(option.value)} onFocus={(event) => setFocusedValue(event.currentTarget.matches(':focus-visible') ? option.value : undefined)} style={{ accentColor: 'var(--kg-color-selection-selected-bg)', height: 20, outline: focusedValue === option.value ? 'var(--kg-foundation-focus-ring-width) solid var(--kg-color-border-focus)' : 'none', outlineOffset: 'var(--kg-foundation-focus-ring-offset)', width: 20 }} type="radio" value={option.value} />{option.label}</label>)}</div></fieldset>;
}

type SelectProps = FieldContract & { options: RadioOption[]; value: string; onValueChange: (value: string) => void } & Omit<SelectHTMLAttributes<HTMLSelectElement>, 'className' | 'style' | 'disabled' | 'required' | 'value' | 'onChange'>;
export function Select({ label, options, value, onValueChange, disabled, errorMessage, helpText, required, onBlur, onFocus, ...props }: SelectProps) {
  const id = useId(); const messageId = `${id}-message`;
  const [focusVisible, setFocusVisible] = useState(false);
  return <label htmlFor={id} style={{ display: 'block' }}><span style={labelStyle}>{label}{required ? ' (필수)' : ''}</span><select {...props} aria-describedby={helpText && !errorMessage ? messageId : undefined} aria-errormessage={errorMessage ? messageId : undefined} aria-invalid={Boolean(errorMessage) || undefined} disabled={disabled} id={id} onBlur={(event) => { setFocusVisible(false); onBlur?.(event); }} onChange={(event) => onValueChange(event.currentTarget.value)} onFocus={(event) => { setFocusVisible(event.currentTarget.matches(':focus-visible')); onFocus?.(event); }} required={required} style={{ ...controlStyle, ...(focusVisible ? focusStyle : {}), borderColor: errorMessage ? 'var(--kg-color-status-negative-border)' : undefined }} value={value}>{options.map((option) => <option disabled={option.disabled} key={option.value} value={option.value}>{option.label}</option>)}</select>{errorMessage || helpText ? <span id={messageId} role={errorMessage ? 'alert' : undefined} style={{ ...messageStyle, color: errorMessage ? 'var(--kg-color-status-negative-fg)' : 'var(--kg-color-fg-secondary)' }}>{errorMessage ?? helpText}</span> : null}</label>;
}

export function SearchField({ label, value, onValueChange, onSearch, onSearchError, placeholder = '검색어를 입력하세요', disabled = false, loading = false }: SearchFieldContract) { assertSearchFieldContract({ label, value, onValueChange, onSearch, onSearchError, placeholder, disabled, loading }); const id = useId(); const [focused, setFocused] = useState(false); const [pending, setPending] = useState(false); const actionLock = useRef(false); const inactive = disabled || loading || pending; const submit = async () => { if (inactive || actionLock.current || !value.trim()) return; actionLock.current = true; setPending(true); try { await onSearch(value.trim()); } catch (error) { try { onSearchError(error); } catch {} } finally { actionLock.current = false; setPending(false); } }; return <div><label htmlFor={id} style={labelStyle}>{label}</label><div style={{ alignItems: 'center', background: 'var(--kg-color-bg-canvas)', border: `1px solid ${focused ? 'var(--kg-color-border-focus)' : 'var(--kg-color-border-strong)'}`, borderRadius: 'var(--kg-foundation-radius-md)', boxSizing: 'border-box', display: 'flex', minHeight: 48, outline: focused ? 'var(--kg-foundation-focus-ring-width) solid var(--kg-color-border-focus)' : 'none', outlineOffset: 'var(--kg-foundation-focus-ring-offset)', paddingLeft: 'var(--kg-foundation-space-3)' }}><input aria-busy={loading || pending || undefined} disabled={inactive} id={id} onBlur={() => setFocused(false)} onChange={(event) => onValueChange(event.currentTarget.value)} onFocus={(event) => setFocused(event.currentTarget.matches(':focus-visible'))} onKeyDown={(event) => { if (event.key === 'Enter' && !event.nativeEvent.isComposing) { event.preventDefault(); void submit(); } }} placeholder={placeholder} style={{ background: 'transparent', border: 0, color: 'var(--kg-color-fg-primary)', flex: 1, font: 'inherit', minWidth: 0, outline: 0 }} type="search" value={value} /><button aria-label="검색어 지우기" disabled={inactive || !value} onBlur={() => setFocused(false)} onClick={() => onValueChange('')} onFocus={() => setFocused(true)} style={{ background: 'transparent', border: 0, color: 'var(--kg-color-fg-secondary)', minHeight: 44, padding: '0 var(--kg-foundation-space-3)' }} type="button">{value ? '지우기' : ''}</button><button aria-busy={loading || pending || undefined} disabled={inactive || !value.trim()} onBlur={() => setFocused(false)} onClick={() => void submit()} onFocus={() => setFocused(true)} style={{ background: 'transparent', border: 0, color: 'var(--kg-color-fg-primary)', minHeight: 44, padding: '0 var(--kg-foundation-space-3)' }} type="button">{loading || pending ? '검색 중' : '검색'}</button></div></div>; }

export function Slider({ label, value, min = 0, max = 100, step = 1, disabled = false, labels, valueLabel = String, showValue = false, onValueChange }: SliderContract) {
  assertSliderContract({ label, value, min, max, step, disabled, labels, valueLabel, showValue, onValueChange }); const id = useId(); const rangeId = `${id}-range`; const [focused, setFocused] = useState(false); const renderedValue = valueLabel(value); const rangeDescription = labels ? `범위 ${labels.min}${labels.mid ? `, 중간 ${labels.mid}` : ''}, ${labels.max}` : undefined;
  return <div style={{ color: 'var(--kg-color-fg-primary)', fontFamily: 'var(--kg-typography-family-web)', maxWidth: 480, width: '100%' }}><div style={{ alignItems: 'center', display: 'flex', justifyContent: 'space-between' }}><label htmlFor={id} style={{ ...labelStyle, marginBottom: 0 }}>{label}</label>{showValue ? <output aria-live="polite" htmlFor={id} style={{ color: disabled ? 'var(--kg-color-fg-disabled)' : 'var(--kg-color-fg-secondary)', fontSize: 'var(--kg-typography-role-label-font-size)' }}>{renderedValue}</output> : null}</div><input aria-describedby={rangeDescription ? rangeId : undefined} aria-valuetext={renderedValue} disabled={disabled} id={id} max={max} min={min} onBlur={() => setFocused(false)} onChange={(event) => onValueChange(normalizeSliderValue(Number(event.currentTarget.value), min, max, step))} onFocus={(event) => setFocused(event.currentTarget.matches(':focus-visible'))} step={step} style={{ accentColor: 'var(--kg-color-action-primary-bg)', cursor: disabled ? 'not-allowed' : 'pointer', height: 44, margin: 0, opacity: disabled ? .45 : 1, outline: focused ? 'var(--kg-foundation-focus-ring-width) solid var(--kg-color-border-focus)' : 'none', outlineOffset: 'var(--kg-foundation-focus-ring-offset)', width: '100%' }} type="range" value={value} />{rangeDescription ? <span id={rangeId} style={{ clip: 'rect(0 0 0 0)', clipPath: 'inset(50%)', height: 1, overflow: 'hidden', position: 'absolute', whiteSpace: 'nowrap', width: 1 }}>{rangeDescription}</span> : null}{labels ? <div aria-hidden="true" style={{ color: disabled ? 'var(--kg-color-fg-disabled)' : 'var(--kg-color-fg-secondary)', display: 'grid', fontSize: 'var(--kg-typography-role-caption-font-size)', gridTemplateColumns: '1fr 1fr 1fr' }}><span>{labels.min}</span><span style={{ textAlign: 'center' }}>{labels.mid}</span><span style={{ textAlign: 'right' }}>{labels.max}</span></div> : null}</div>;
}

export function DateTimeField({ label, kind, value, onValueChange, min, max, disabled = false, required = false, helpText, errorMessage }: DateTimeFieldContract) { assertDateTimeFieldContract({ label, kind, value, onValueChange, min, max, disabled, required, helpText, errorMessage }); const id = useId(); const messageId = `${id}-message`; const [focusVisible, setFocusVisible] = useState(false); return <label htmlFor={id} style={{ display: 'block' }}><span style={labelStyle}>{label}{required ? ' (필수)' : ''}</span><input aria-describedby={helpText && !errorMessage ? messageId : undefined} aria-errormessage={errorMessage ? messageId : undefined} aria-invalid={Boolean(errorMessage) || undefined} disabled={disabled} id={id} max={max} min={min} onBlur={() => setFocusVisible(false)} onChange={(event) => onValueChange(event.currentTarget.value)} onFocus={(event) => setFocusVisible(event.currentTarget.matches(':focus-visible'))} required={required} style={{ ...controlStyle, ...(focusVisible ? focusStyle : {}), borderColor: errorMessage ? 'var(--kg-color-status-negative-border)' : undefined }} type={kind} value={value} />{errorMessage || helpText ? <span id={messageId} role={errorMessage ? 'alert' : undefined} style={{ ...messageStyle, color: errorMessage ? 'var(--kg-color-status-negative-fg)' : 'var(--kg-color-fg-secondary)' }}>{errorMessage ?? helpText}</span> : null}</label>; }
