import { useEffect, useRef, useState } from 'react';
import { AccessibilityInfo, ActivityIndicator, Platform, Pressable, Text, useColorScheme, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { getNativeTheme } from '@kimgseok/design-tokens/native';
import { normalizeProgress, normalizeToastDuration, type CalloutContract, type FeedbackTone, type ProgressContract, type SpinnerContract, type ToastContract } from './contracts';

function useTheme() { return getNativeTheme(useColorScheme() === 'dark' ? 'dark' : 'light', Platform.OS === 'android' ? 'android' : 'ios'); }
function useReduceMotion() { const [reduced, setReduced] = useState<boolean | null>(null); useEffect(() => { void AccessibilityInfo.isReduceMotionEnabled().then(setReduced); const subscription = AccessibilityInfo.addEventListener('reduceMotionChanged', setReduced); return () => subscription.remove(); }, []); return reduced; }
const spinnerSizes = { sm: 16, md: 24, lg: 32 } as const;
export function NativeSpinner({ accessibilityLabel = '로딩 중', size = 'md' }: SpinnerContract) { const theme = useTheme(); const reduced = useReduceMotion(); const diameter = spinnerSizes[size]; return <View accessibilityLabel={accessibilityLabel} accessibilityRole="progressbar" accessibilityState={{ busy: true }}>{reduced ? <View style={{ borderColor: theme.color.semantic.feedback.spinner.track, borderRadius: diameter / 2, borderTopColor: theme.color.semantic.feedback.spinner.indicator, borderWidth: 2, height: diameter, width: diameter }} /> : <ActivityIndicator color={theme.color.semantic.feedback.spinner.indicator} size={diameter} />}</View>; }
export function NativeProgress({ accessibilityLabel, value, size = 'md' }: ProgressContract) { const theme = useTheme(); const reduced = useReduceMotion(); const normalized = normalizeProgress(value); if (normalized === undefined) return <View accessibilityLabel={accessibilityLabel} accessibilityRole="progressbar" accessibilityState={{ busy: true }} style={{ alignItems: 'center', justifyContent: 'center', minHeight: size === 'sm' ? 16 : 24, width: '100%' }}>{reduced === false ? <ActivityIndicator color={theme.color.semantic.feedback.spinner.indicator} size={size === 'sm' ? 'small' : 'large'} /> : <View accessible={false} style={{ flexDirection: 'row', gap: size === 'sm' ? 3 : 5 }}>{[0, 1, 2].map((dot) => <View key={dot} style={{ backgroundColor: dot === 1 ? theme.color.semantic.feedback.progress.fill : theme.color.semantic.feedback.progress.track, borderRadius: 999, height: size === 'sm' ? 6 : 10, width: size === 'sm' ? 6 : 10 }} />)}</View>}</View>; const percent = Math.round(normalized * 100); return <View accessibilityLabel={accessibilityLabel} accessibilityRole="progressbar" accessibilityValue={{ min: 0, max: 100, now: percent }} style={{ backgroundColor: theme.color.semantic.feedback.progress.track, borderRadius: 999, height: size === 'sm' ? 4 : 8, overflow: 'hidden', width: '100%' }}><View style={{ backgroundColor: theme.color.semantic.feedback.progress.fill, borderRadius: 999, height: '100%', width: `${normalized * 100}%` }} /></View>; }

function nativeStatusColors(theme: ReturnType<typeof useTheme>, tone: FeedbackTone) { if (tone === 'neutral') return { background: theme.color.semantic.bg.surface, border: theme.color.semantic.border.strong, foreground: theme.color.semantic.fg.primary }; const status = theme.color.semantic.status[tone]; return { background: status.bg, border: status.border, foreground: status.fg }; }

function NativeToast({ toast, bottomInset }: { toast: ToastContract; bottomInset: number }) {
  const { open, message, tone = 'neutral', durationMs, action, onOpenChange } = toast; const theme = useTheme(); const [pending, setPending] = useState(false); const lock = useRef(false);
  const normalizedDuration = normalizeToastDuration(durationMs, Boolean(action) || tone === 'negative'); const persistent = normalizedDuration === null;
  useEffect(() => { if (!open || normalizedDuration === null) return; const timer = setTimeout(() => onOpenChange(false), normalizedDuration); return () => clearTimeout(timer); }, [normalizedDuration, onOpenChange, open]);
  if (!open) return null;
  const runAction = async () => { if (!action || lock.current) return; lock.current = true; setPending(true); try { await action.onAction(); onOpenChange(false); } catch (error) { try { action.onError(error); } catch { /* durable caller error surface owns secondary failure */ } } finally { lock.current = false; setPending(false); } };
  const accent = tone === 'neutral' ? theme.color.semantic.border.strong : theme.color.semantic.status[tone].border;
  return <View accessibilityLiveRegion={tone === 'negative' ? 'assertive' : 'polite'} accessibilityRole={tone === 'negative' ? 'alert' : 'summary'} pointerEvents="auto" style={{ alignItems: 'center', backgroundColor: theme.color.semantic.feedback.overlay.bg, borderLeftColor: accent, borderLeftWidth: 4, borderRadius: theme.foundation.radius.lg, bottom: bottomInset + 24, flexDirection: 'row', gap: 12, left: 16, minHeight: 48, paddingHorizontal: 16, paddingVertical: 12, position: 'absolute', right: 16 }}><Text style={[theme.typography.role.body, { color: theme.color.semantic.feedback.overlay.fg, flex: 1 }]}>{message}</Text>{action ? <Pressable accessibilityRole="button" accessibilityState={{ busy: pending, disabled: pending }} disabled={pending} onPress={() => void runAction()} style={{ justifyContent: 'center', minHeight: 44 }}><Text style={[theme.typography.role.label, { color: theme.color.semantic.feedback.overlay.fg, textDecorationLine: 'underline' }]}>{pending ? `${action.label} 중` : action.label}</Text></Pressable> : null}{persistent ? <Pressable accessibilityLabel="알림 닫기" accessibilityRole="button" disabled={pending} onPress={() => onOpenChange(false)} style={{ justifyContent: 'center', minHeight: 44 }}><Text style={[theme.typography.role.label, { color: theme.color.semantic.feedback.overlay.fg }]}>닫기</Text></Pressable> : null}</View>;
}

export function NativeToastHost({ toast }: { toast: ToastContract | null }) { const insets = useSafeAreaInsets(); return <View pointerEvents="box-none" style={{ bottom: 0, left: 0, position: 'absolute', right: 0, top: 0, zIndex: 1000 }}>{toast ? <NativeToast bottomInset={insets.bottom} toast={toast} /> : null}</View>; }

export function NativeCallout({ title, description, tone = 'info', announce = false }: CalloutContract) { const theme = useTheme(); const colors = nativeStatusColors(theme, tone); return <View accessibilityLabel={`${title}${description ? `. ${description}` : ''}`} accessibilityLiveRegion={announce ? 'polite' : 'none'} accessibilityRole="summary" style={{ backgroundColor: colors.background, borderColor: colors.border, borderRadius: theme.foundation.radius.lg, borderWidth: 1, gap: 4, padding: 16 }}><Text accessible={false} style={[theme.typography.role.label, { color: colors.foreground }]}>{title}</Text>{description ? <Text accessible={false} style={[theme.typography.role.body, { color: colors.foreground }]}>{description}</Text> : null}</View>; }
